debug: false
installation_path: /usr/local/ip2location
ip2api:
    plan: Free
    url: https://api.ip2location.io/
    max_errors: 5
jsonlogs: false
loglevel: debug
redis:
    ip2location:
        auth: ip2location
        db: 1
        host: 127.0.0.1
        pass: password
        port: "6379"
    pfsense:
        auth: ip2location
        db: 2
        host: 127.0.0.1
        pass: password
        port: "6379"
service:
    bind_host: 192.168.1.51
    bind_port: "9999"
    use_ssl: false
    ssl_cert: ./IP2Location+SSL.crt
    ssl_key: ./IP2Location+SSL.pem
    ingest_logs: /api/filterlog
    ip2l_results: /api/results
    ip2geomap: /index.html
    ip_requests: /api/ip2location
    healthcheck: /health

use_cache: true
use_redis: true
apikeys:
  - rAtRpIX3LlpKH4IzBRG58g18MFDb7keiDBV9Gq6e9Au4kcHEPqXZv1RU14MaVIe0
  - qvqiDj7cUXaikId0RuXgDl2BsK5cbMizSmqELEs2FlLCjY83CuxhbhUImvs4L03P"