debug: false
installation_path: /usr/local/ip2location
ip2api:
    key: DC65E99DD9FBDAD2D244DE7E148D02B5
    plan: Free
    url: https://api.ip2location.io/
jsonlogs: false
loglevel: debug
redis:
    ip2location:
        auth: ip2location
        db: 1
        host: 127.0.0.1
        pass: password
        port: "6379"
    pfsense:
        auth: ip2location
        db: 2
        host: 127.0.0.1
        pass: password
        port: "6379"
service:
    bind_host: 192.168.1.51
    bind_port: "9999"
use_cache: true
use_redis: true
