version: "3.6"
services:
  redis-stack:
    command:
      - "/entrypoint.sh"
    container_name: "redis-stack"
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379/tcp"
      - "8001:8001/tcp"
    volumes:
      - data:/data
    networks:
      - backend
      - pfsense
  ip2location-pfsense:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "ip2location-pfsense"
    environment:
      - "REDIS_HOST=redis-stack"
      - "REDIS_PORT=6379"

